fix: exported Makefile variables caused noise (#871)
Setting the variables using 'export' causes them to execute the shell
commands for *every* make command. They are only useful for `kind` make
targets, so the error messages from their run in all other instances
produces a lot of unrelevant log messages.

eg:
```
$make test-sublinters
docker run --rm -v github.com/ovrclk/akash:/workspace -w /workspace golangci/golangci-lint:v1.31.0-alpine golangci-lint run ./... --disable-all --deadline=5m --enable deadcode
Error: No such container: kube-control-plane
Error: No such container: kube-control-plane
docker run --rm -v /home/ropes/go/src/github.com/ovrclk/akash:/workspace -w /workspace golangci/golangci-lint:v1.31.0-alpine golangci-lint run ./... --disable-all --deadline=5m --enable misspell --no-config
Error: No such container: kube-control-plane
Error: No such container: kube-control-plane
docker run --rm -v /home/ropes/go/src/github.com/ovrclk/akash:/workspace -w /workspace golangci/golangci-lint:v1.31.0-alpine golangci-lint run ./... --disable-all --deadline=5m --enable goerr113
Error: No such container: kube-control-plane
Error: No such container: kube-control-plane
```